name: "rd-winrm-plugin"
rundeckPluginVersion: 1.2
author: "© 2017, Rundeck, Inc."
date: "Fri Feb 03 22:29:35 UTC 2017"
version: "1.5.2"
url: "http://rundeck.com"
providers:
  - name: WinRMexe
    title: WinRM Executor
    description: Executing Scripts or commands on remote windows computer
    service: NodeExecutor
    plugin-type: script
    script-interpreter: ruby
    script-file: winrmexe.rb
#    script-args: ${config.realm} ${config.username} ${config.password} ${node.hostname} ${exec.command}
    interpreter-args-quoted: true
    config:
      - name: krb5_realm
        title: Kerberos Realm
        type: String
        required: false
        description: "Kerberos Realm FQDN in capital letters.Can be overridden by a Node attribute named 'krb5_realm'."
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "krb5_realm"
      - name: passwordStoragePath
        title: Password Storage Path
        type: String
        required: false
        description: "Path to the Password to use within Rundeck Storage. E.g. keys/path/my.password. Can be overridden by a Node attribute named 'ssh-password-storage-path'."
        scope: Instance
        renderingOptions:
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
          storage-file-meta-filter: "Rundeck-data-type=password"
          instance-scope-node-attribute: "password-storage-path"
      - name: authtype
        title: Auth type
        description: "Authentication type.Can be overridden by a Node attribute named 'authtype'."
        type: Select
        values: "negotiate, ssl, kerberos, plaintext"
        default: "plaintext"
        required: true
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "authtype"
      - name: allowoverride
        title: Allow Override
        description: "Gives possibility to override hostname, username (and password) in job options.Can be overridden by a Node attribute named 'allowoverride'."
        type: Select
        values: "none, host, user, all"
        default: "none"
        required: true
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "allowoverride"
      - name: winrmport
        title: WinRM port
        description: "WinRM port (Default: 5985/5986 for http/https).Can be overridden by a Node attribute named 'winrmport'."
        type: String
        default: "5985"
        required: true
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "winrmport"
      - name: shell
        title: Shell
        description: "Windows interpreter.Can be overridden by a Node attribute named 'shell'."
        type: Select
        values: "cmd, powershell, wql"
        default: 'powershell'
        required: true
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "shell"
      - name: winrmtimeout
        title: WinRM timeout
        description: "timeout in seconds default: 60. Can be overridden by a Node attribute named 'winrmtimeout'."
        type: Integer
        required: false
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "winrmtimeout"
      - name: nosslpv
        title: No SSL Peer Verification
        type: Boolean
        description: "Enable/Disable the ssl peer verificacion ( eg: no_ssl_peer_verification => true). Can be overridden by a Node attribute named 'no-ssl-peer-verification'."
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "no-ssl-peer-verification"          
  - name: WinRMcp
    title: WinRM File Copier
    service: FileCopier
    plugin-type: script
    script-interpreter: ruby
    script-file: winrmcp.rb
    script-args: ${node.hostname} ${file-copy.file} ${file-copy.destination}
    config:
      - name: krb5_realm
        title: Kerberos Realm
        type: String
        required: false
        description: "Kerberos Realm FQDN in capital letters.Can be overridden by a Node attribute named 'krb5_realm'."
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "krb5_realm"
      - name: passwordStoragePath
        title: Password Storage Path
        type: String
        required: false
        description: "Path to the Password to use within Rundeck Storage. E.g. keys/path/my.password. Can be overridden by a Node attribute named 'ssh-password-storage-path'."
        scope: Instance
        renderingOptions:
          selectionAccessor: "STORAGE_PATH"
          valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
          storage-path-root: "keys"
          storage-file-meta-filter: "Rundeck-data-type=password"
          instance-scope-node-attribute: "password-storage-path"
      - name: authtype
        title: Auth type
        description: "Authentication type.Can be overridden by a Node attribute named 'authtype'."
        type: Select
        values: "negotiate, ssl, kerberos, plaintext"
        default: "plaintext"
        required: true
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "authtype"
      - name: allowoverride
        title: Allow Override
        description: "Gives possibility to override hostname, username (and password) in job options.Can be overridden by a Node attribute named 'allowoverride'."
        type: Select
        values: "none, host, user, all"
        default: "none"
        required: true
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "allowoverride"
      - name: winrmport
        title: WinRM port
        description: "WinRM port (Default: 5985/5986 for http/https).Can be overridden by a Node attribute named 'winrmport'."
        type: String
        default: "5985"
        required: true
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "winrmport"
      - name: shell
        title: Shell
        description: "Windows interpreter. Should be same as in Executor.Can be overridden by a Node attribute named 'shell'."
        type: Select
        values: "cmd, powershell, wql"
        default: 'powershell'
        required: true
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "shell"
      - name: winrmtimeout
        title: WinRM timeout
        description: "timeout in seconds default: 60. Can be overridden by a Node attribute named 'winrmtimeout'."
        type: Integer
        required: false
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "winrmtimeout"
      - name: nosslpv
        title: No SSL Peer Verification
        type: Boolean
        description: "Enable/Disable the ssl peer verificacion ( eg: no_ssl_peer_verification => true). Can be overridden by a Node attribute named 'no-ssl-peer-verification'."
        scope: Instance
        renderingOptions:
          instance-scope-node-attribute: "no-ssl-peer-verification" 
